import { IndexTableHeading } from "@shopify/polaris/build/ts/src/components/IndexTable";
import { NonEmptyArray } from "@shopify/polaris/build/ts/src/types";

export const AD_REPORT_TABLE_HEADERS: NonEmptyArray<IndexTableHeading> = [
  { title: "Name", alignment: "start" },
  { title: "Source", alignment: "center" },
  { title: "View Content", alignment: "end" },
  { title: "Add to Cart", alignment: "end" },
  { title: "Initiate Checkout", alignment: "end" },
  { title: "Purchases", alignment: "end" },
  { title: "Total sales", alignment: "end" },
];

export const INITIAL_AD_REPORT_FILTER = {
  search: "",
};

// TODO: Mock data will be deleted later
export const MOCK_AD_REPORT_DATA = [
  {
    id: "1",
    name: "Campaign name",
    source: "TikTok",
    viewContent: 100,
    addToCart: 100,
    initiateCheckout: 100,
    purchases: 100,
    totalSales: "$100.02",
  },
  {
    id: "2",
    name: "Campaign name",
    source: "TikTok",
    viewContent: 200,
    addToCart: 200,
    initiateCheckout: 200,
    purchases: 100,
    totalSales: "$100.02",
  },
  {
    id: "3",
    name: "Campaign name",
    source: "TikTok",
    viewContent: 300,
    addToCart: 300,
    initiateCheckout: 300,
    purchases: 100,
    totalSales: "$100.02",
  },
  {
    id: "4",
    name: "Undetected",
    source: null,
    viewContent: 400,
    addToCart: 400,
    initiateCheckout: 400,
    purchases: 100,
    totalSales: "$100.02",
  },
  {
    id: "5",
    name: "Tulipan ArCampaign namemchair",
    source: "TikTok",
    viewContent: 500,
    addToCart: 500,
    initiateCheckout: 500,
    purchases: 100,
    totalSales: "$100.02",
  },
  {
    id: "6",
    name: "Undetected",
    source: null,
    viewContent: 600,
    addToCart: 600,
    initiateCheckout: 600,
    purchases: 100,
    totalSales: "$100.02",
  },
  {
    id: "7",
    name: "Undetected",
    source: null,
    viewContent: 700,
    addToCart: 700,
    initiateCheckout: 700,
    purchases: 100,
    totalSales: "$100.02",
  },
  {
    id: "8",
    name: "Ethan Wall Clock",
    source: "TikTok",
    viewContent: 800,
    addToCart: 800,
    initiateCheckout: 800,
    purchases: 100,
    totalSales: "$100.02",
  },
  {
    id: "9",
    name: "Vibe Retro Coffee Table",
    source: "TikTok",
    viewContent: 900,
    addToCart: 900,
    initiateCheckout: 900,
    purchases: 100,
    totalSales: "$100.02",
  },
  {
    id: "10",
    name: "Cascade Center Table",
    source: "TikTok",
    viewContent: 1000,
    addToCart: 1000,
    initiateCheckout: 1000,
    purchases: 100,
    totalSales: "$100.02",
  },
];
